close #2: Check hierarchy as connected graph
AdaptaBrasil/data_validate pull request #51
Opened 2024-01-11 22:50 UTC by MarioCarvalhoBr

Adicionei 3 verificações: 

1. Verificar se os códigos da planilha de composição estão na planilha de descrição
2. Verificar se existe ciclos no grafo
3. Verificar se existem grafos desconexos

2024-01-11 23:50 UTC, pedro-andrade-inpe requested changes

2024-01-11 23:50 UTC, pedro-andrade-inpe commented on main.py
> +from src.myparser import print_versions, verify_structure_folder_files, verify_sp_description_parser, verify_spelling_text, verify_sp_description_titles_uniques, verify_sp_description_text_capitalize
nao sei se o local é aqui, mas a verificacao da composicao deve vir logo apos a verificacao dos arquivos, ela esta sendo feita por ultimo

2024-01-11 23:50 UTC, pedro-andrade-inpe commented on src/util/graph.py
> +            errors.append("Grafos desconectados encontrados: Grafo " + str(i) + ": [" + imprimir_grafo(sg) + "]")
o usuario nao sabe o que é grafo. trocar por indicadores desconectados

2024-01-11 23:50 UTC, pedro-andrade-inpe commented on src/util/graph.py
> +        errors.append("Códigos ausentes na planilha de descrição: " + str(codigos_faltantes))
diga em que arquivo aparece e em que arquivo nao aparece. melhor do que se referrir a planilhas disso ou daquilo

2024-01-12 11:11 UTC, pedro-andrade-inpe commented on src/util/graph.py
> +        errors.append("Códigos ausentes na planilha de descrição: " + str(codigos_faltantes))
Close #3

2024-01-12 11:11 UTC, pedro-andrade-inpe commented
Close #3

2024-01-12 13:37 UTC, MarioCarvalhoBr commented on main.py
> +from src.myparser import print_versions, verify_structure_folder_files, verify_sp_description_parser, verify_spelling_text, verify_sp_description_titles_uniques, verify_sp_description_text_capitalize
Corrigido. Adicionei a verificação de composição após a verificação de arquivos.
![Screenshot from 2024-01-12 09-37-13](https://github.com/AdaptaBrasil/data_validate/assets/12476879/c5bc5956-f20c-496e-9e39-e1e3c61a1c04)

2024-01-13 18:50 UTC, MarioCarvalhoBr commented
Correção do texto de verificação.

2024-01-14 11:19 UTC, pedro-andrade-inpe approved these changes

2024-01-14 11:19 UTC, merged